services:
  mysql-master:
    image: mysql:8
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
      - ./master/init/master-init.sql:/docker-entrypoint-initdb.d/master-init.sql
    ports:
      - "3306:3306"
    networks:
      - replication
    depends_on:
      - prometheus

  mysql-slave1:
    image: mysql:8
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./slave1/my.cnf:/etc/mysql/my.cnf
      - ./slave1/init/slave-init.sh:/docker-entrypoint-initdb.d/slave-init.sh
    ports:
      - "3307:3306"
    networks:
      - replication
    depends_on:
      - mysql-master
      - prometheus

  mysql-slave2:
    image: mysql:8
    container_name: mysql-slave2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./slave2/my.cnf:/etc/mysql/my.cnf
      - ./slave2/init/slave-init.sh:/docker-entrypoint-initdb.d/slave-init.sh
    ports:
      - "3308:3306"
    networks:
      - replication
    depends_on:
      - mysql-master
      - prometheus

  mysqld_exporter_master:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter_master
    environment:
      DATA_SOURCE_NAME: exporter_user:exporter_password@(mysql-master:3306)/
    command:
     - "--mysqld.username=exporter_user:exporter_password"
     - "--mysqld.address=mysql-master:3306"
    networks:
      - replication
    depends_on:
      - mysql-master

  mysqld_exporter_slave1:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter_slave1
    environment:
      DATA_SOURCE_NAME: exporter_user:exporter_password@(mysql-slave1:3306)/
    command:
     - "--mysqld.username=exporter_user:exporter_password"
     - "--mysqld.address=mysql-slave1:3306"
    networks:
      - replication
    depends_on:
      - mysql-slave1

  mysqld_exporter_slave2:
    image: prom/mysqld-exporter:latest
    container_name: mysqld_exporter_slave2
    environment:
      DATA_SOURCE_NAME: exporter_user:exporter_password@(mysql-slave2:3306)/
    command:
     - "--mysqld.username=exporter_user:exporter_password"
     - "--mysqld.address=mysql-slave2:3306"
    networks:
      - replication
    depends_on:
      - mysql-slave2

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - replication

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - replication
    depends_on:
      - prometheus

networks:
  replication:
    driver: bridge

volumes:
  mysql_master_data:
  mysql_slave1_data:
  mysql_slave2_data:
  grafana_data:
