global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysql-master'
    static_configs:
      - targets: ['mysqld_exporter_master:9104']

  - job_name: 'mysql-slave1'
    static_configs:
      - targets: ['mysqld_exporter_slave1:9104']

  - job_name: 'mysql-slave2'
    static_configs:
      - targets: ['mysqld_exporter_slave2:9104']
